<nav class="navbar navbar-dark navbar-expand-sm p-0">
	<div class="container">		

		<button class="navbar-toggler" type="button"
			data-toggle="collapse" data-target="#myTogglerNav" aria-controls="myTogglerNav" 
			aria-expanded="false" 
			aria-label="Toggle Navigation">
				<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="myTogglerNav">
			<div class="navbar-nav ml-auto">
				<a class="nav-item nav-link" href="/">Home</a>
				<a class="nav-item nav-link" href="/about">About</a>
				<a class="nav-item nav-link" href="/changelog">Changelog</a>	
				<!-- <a class="nav-item nav-link" href="#blog">Privacy</a> -->									
			</div>
		</div>
	</div>
</nav>